= {project-name} (Markdown to AsciiDoc)
Dan Allen <https://github.com/mojavelinux>
v1.0.0.alpha.6, 2018-06-26
// Aliases:
:project-name: Kramdown AsciiDoc
:project-handle: kramdown-asciidoc
// Settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: preamble
:toclevels: 1
endif::[]
ifdef::env-github[]
:status:
:!toc-title:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]
// URIs:
:uri-repo: https://github.com/asciidoctor/kramdown-asciidoc
:uri-asciidoc: https://asciidoctor.org/docs/what-is-asciidoc/#what-is-asciidoc
:uri-asciidoctor: https://asciidoctor.org
:uri-kramdown: https://kramdown.gettalong.org
:uri-rvm: https://rvm.io
:uri-rvm-install: https://rvm.io/rvm/install
:uri-ci-travis: https://travis-ci.org/asciidoctor/kramdown-asciidoc
:uri-ci-travis-img: https://img.shields.io/travis/asciidoctor/kramdown-asciidoc/master.svg
:uri-gem: https://rubygems.org/gems/kramdown-asciidoc
:uri-gem-img: https://img.shields.io/gem/v/kramdown-asciidoc.svg?label=gem

ifdef::status[]
image:{uri-gem-img}[Gem Version,link={uri-gem}]
image:{uri-ci-travis-img}[Build Status (Travis CI),link={uri-ci-travis}]
endif::[]

{uri-repo}[{project-name}] (gem: *{project-handle}*) is a {uri-kramdown}[kramdown] extension for converting Markdown documents to {uri-asciidoc}[AsciiDoc].
Notably, the converter generates modern AsciiDoc syntax suitable for use with {uri-asciidoctor}[Asciidoctor].

== Prerequisites

To install and run {project-name}, you need Ruby 2.4 or better installed and a few RubyGems (aka gems).
We'll explain how to install the gems in the next section.

To check whether you have Ruby installed, and which version, run the following command:

 $ ruby -v

If Ruby is not installed, you can install it using {uri-rvm}[RVM] (or, if you prefer, the package manager for your system).
We generally recommend using RVM because it allows you to install gems without requiring elevated privileges or messing with system libraries.

== Installation

{project-name} is published to RubyGems.org as a pre-release gem named *{project-handle}*.

You can install the pre-release version using the following command:

 $ gem install kramdown-asciidoc --pre

Installing this gem makes the `kramdoc` command available on your $PATH.

TIP: To test a feature that's not yet released, you can <<Development,run the application from source>>.

== Usage

To convert a Markdown file to AsciiDoc using {project-name}, pass the name of the file to the `kramdoc` command as follows:

 $ kramdoc sample.md

By default, the `kramdoc` command automatically creates the output file [.path]_sample.adoc_ in the same folder as the input file.
This path is calculated by removing the Markdown file extension, `.md`, and replacing it with the AsciiDoc file extension, `.adoc`.

NOTE: The converter assumes the input uses the GitHub-flavor Markdown (GFM) syntax.

If you want to direct the output to a different file, pass the name of that file to the `kramdoc` command using the `-o` option as follows:

 $ kramdoc -o result.adoc sample.md

To direct the output to the console (i.e., STDOUT) instead of a file, use the special value `-` as follows:

 $ kramdoc -o - sample.md

To see all the options the `kramdoc` command accepts, pass the `-h` option to the `kramdoc` command as follows:

 $ kramdoc -h

== Development

To help develop {project-name}, or to simply test-drive the development version, you need to retrieve the source from GitHub.
Follow the instructions below to learn how to clone the source and run the application from source (i.e., your clone).

=== Retrieve the source code

Simply copy the {uri-repo}[GitHub repository URL] and pass it to the `git clone` command:

[subs=attributes+]
 $ git clone {uri-repo}

Next, switch to the project directory:

[subs=attributes+]
 $ cd {project-handle}

=== Prepare RVM (optional)

We recommend using {uri-rvm}[RVM] when developing applications with Ruby.
We like RVM because it keeps the dependencies required by the project isolated from the rest of your system.
Follow the {uri-rvm-install}[installation instructions] on the RVM site to setup RVM and install Ruby.

Once you have RVM setup, switch to the RVM-managed version of Ruby recommended by the project using this command:

 $ rvm use

The recommended version of Ruby is defined in the [.path]_.ruby-version_ file at the root of the project.

=== Install the dependencies

The dependencies needed to use {project-name} are defined in the [.path]_Gemfile_ at the root of the project.
You'll use Bundler to install these dependencies.

To check if you have Bundler available, use the `bundle` command to query the version installed:

 $ bundle --version

If Bundler is not installed, use the `gem` command to install it.

 $ gem install bundler

Then, use the `bundle` command to install the project dependencies under the project directory:

 $ bundle --path=.bundle/gems

NOTE: You must invoke `bundle` from the project's root directory so it can locate the [.path]_Gemfile_.

=== Usage

When running the `kramdoc` command from source, you must prefix the command with `bundle exec`:

 $ bundle exec kramdoc sample.md

To avoid having to do this, or make the `kramdoc` command available from anywhere, you need to build the development gem and install it.

== Alternatives

* https://github.com/bodiam/markdown-to-asciidoc[markdown-to-asciidoc] (Java library)
* http://pandoc.org[pandoc] (Haskell-based CLI tool)

== Authors

*{project-name}* was written by {email}[{author}].

== Copyright

Copyright (C) 2016-2018 OpenDevise Inc. (on behalf of the Asciidoctor Project).
Free use of this software is granted under the terms of the MIT License.

See the link:LICENSE.adoc[LICENSE] file for details.
