require 'kramdown'
require_relative 'kramdown-asciidoc/kramdown_ext/parser/html'
require_relative 'kramdown-asciidoc/core_ext/regexp/is_match'
require_relative 'kramdown-asciidoc/api'
require_relative 'kramdown-asciidoc/converter'
require_relative 'kramdown-asciidoc/writer'
autoload :Pathname, 'pathname'
autoload :YAML, 'yaml'
